### ISSUE TITLE
NoSuchMethodError: The getter 'iterator' was called on null.

### ISSUE THREAD

**Issue by xsahil03x** [pulyaevskiy/test-coverage#13]
It was working fine for the past builds but suddenly stopped working yesterday.

This is my yaml config: https://github.com/xsahil03x/super_enum/blob/master/.github/workflows/push.yml

Here's the full log.
```
2019-12-02T20:17:38.8214424Z Installed executable test_coverage.
2019-12-02T20:17:38.8273896Z Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
2019-12-02T20:17:38.8274333Z You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):
2019-12-02T20:17:38.8274438Z 
2019-12-02T20:17:38.8274753Z   export PATH="$PATH":"$HOME/.pub-cache/bin"
2019-12-02T20:17:38.8274814Z 
2019-12-02T20:17:38.8274926Z Activated test_coverage 0.4.0.
2019-12-02T20:17:39.1662717Z Found 1 test files.
2019-12-02T20:17:39.1773272Z Generated test-all script in test/.test_coverage.dart. Please make sure it is added to .gitignore.
2019-12-02T20:17:39.6580057Z Unhandled exception:
2019-12-02T20:17:39.6580900Z NoSuchMethodError: The getter 'iterator' was called on null.
2019-12-02T20:17:39.6581025Z Receiver: null
2019-12-02T20:17:39.6581115Z Tried calling: iterator
2019-12-02T20:17:39.6597401Z #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
2019-12-02T20:17:39.6597793Z #1      new List.from (dart:core-patch/array_patch.dart:52:19)
2019-12-02T20:17:39.6597925Z #2      new VM._fromJson (package:vm_service/vm_service.dart:6420:19)
2019-12-02T20:17:39.6598049Z #3      VM.parse (package:vm_service/vm_service.dart:6363:32)
2019-12-02T20:17:39.6598208Z #4      createServiceObject (package:vm_service/vm_service.dart:69:34)
2019-12-02T20:17:39.6598324Z #5      VmService._processResponse (package:vm_service/vm_service.dart:1862:28)
2019-12-02T20:17:39.6598455Z #6      VmService._processMessageStr (package:vm_service/vm_service.dart:1842:7)
2019-12-02T20:17:39.6598584Z #7      VmService._processMessage (package:vm_service/vm_service.dart:1793:7)
2019-12-02T20:17:39.6598710Z #8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
2019-12-02T20:17:39.6598835Z #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
2019-12-02T20:17:39.6598963Z #10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
2019-12-02T20:17:39.6599070Z #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
2019-12-02T20:17:39.6599200Z #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
2019-12-02T20:17:39.6599327Z #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
2019-12-02T20:17:39.6599897Z #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
2019-12-02T20:17:39.6600336Z #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
2019-12-02T20:17:39.6600706Z #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
2019-12-02T20:17:39.6918847Z ##[error]Process completed with exit code 255.
```

**Comment by xsahil03x** [comment]
Closing as automatically fixed.
